main: rip.artemis.telescope.Telescope
name: Telescope
description: zoom zoom
version: 1.0
author: Steven_
api-version: 1.15

commands:
  telescope:
    aliases: [zoom, telescopes, givetelescope]
permissions:
  telescope.givecommand:
    default: op